### ISSUE TITLE
User Authentication

### ISSUE THREAD

**Issue by AnaNika10** [AnaNika10/ConSpace#1]
**Description:**
As a ConSpace user, I want a secure and convenient way to sign up, sign in, and sign out of the platform, both from the frontend user interface and through backend services. This will ensure my personal information is protected and that I can access the platform efficiently.

**Acceptance Criteria:**

**1. User Signup:**
- Given that I am a new user, when I visit the website, I should be presented with a user registration form on the frontend.
- The registration form should request necessary information, including username, email address, and password.
- Password validation should include minimum length and complexity requirements.
- When I submit the registration form, my data should be securely transmitted to the backend.
- The backend should store my information securely and provide a unique identifier (user ID) for my account.

**2. User Signin:**
- When I return to the website as a registered user, I should find a login form on the frontend.
- The login form should prompt me to enter either my username or email and my password.
- After entering valid credentials, clicking the "Sign In" button should send my data to the backend for verification.
- The backend should compare the provided credentials with the stored user data and respond with a success message and an authentication token if the credentials are valid.

**3. Session Management:**
- Once I am signed in, I should remain authenticated across different pages and interactions within the website.
- If I close the browser or log out manually, my session should be invalidated unless Remember me option has been checked.
- Invalid or expired sessions should redirect me to the login page when attempting to access protected resources.

**4. User Signout:**
- While signed in, I should have the option to sign out from any page on the website.
- Clicking the "Sign Out" option should trigger a request to the backend to invalidate the current session.
- After successful signout, I should be redirected to the homepage or a designated landing page.

**5. Error Handling:**
- If I provide incorrect credentials during sign in, I should receive appropriate error messages indicating the issue.
- For any critical errors during authentication processes, a user-friendly error message should be displayed on the frontend.

**6. Security:**
- Passwords stored in the backend should be securely hashed and salted to prevent unauthorized access to user information.
- Backend APIs should implement security mechanisms (such as JWT tokens) to protect against malicious attacks.

By implementing this user story, users will have a seamless and secure experience when signing up, signing in, and signing out of the platform from both frontend and backend perspectives.

**Comment by milicar7** [comment]
[https://github.com/AnaNika10/ConSpace/issues/9](url)

**Comment by milicar7** [comment]
#10

**Comment by milicar7** [comment]
#9 
#10 
#22
#23
#24
#25
#26
#27
#28
#37
#51
#61
#63
#65
#81
#82
#83
