### ISSUE TITLE
Create Seminar Schedule on FE

### ISSUE THREAD

**Issue by milicar7** [AnaNika10/ConSpace#43]
Seminar Schedule component will list all seminars for the conference by date and time. Implemented as a list of seminars.

AC:
Seminar Schedule component is implemented on FE.

**Comment by marijal74** [comment]
https://devexpress.github.io/devextreme-reactive/react/scheduler/

**Comment by marijal74** [comment]
Blocked, explanation provided in: https://github.com/AnaNika10/ConSpace/pull/73
