### ISSUE TITLE
Create My Seminar Schedule on FE

### ISSUE THREAD

**Issue by milicar7** [AnaNika10/ConSpace#44]
My Seminar Schedule component will list all seminars that user chose to attend by date and time. Implemented as daily calendar.
Implement:
* adding/removing seminars
* filter by speaker
* add note for seminar in schedule
* toggle preview between day and week
* return data by user
* switch to integer instead of GUID for conferenceRoomId
AC:
My Seminar Schedule component is implemented on FE.

**Comment by marijal74** [comment]
https://devexpress.github.io/devextreme-reactive/react/scheduler/

**Comment by marijal74** [comment]
Currently, I have implemented the calendar but I'm blocked by #22 , #23 (I suppose token data extraction will be done in these tasks), as I need userId passed in token during authentication to fetch data from server.

@milicar7
